### PR TITLE
VBS22-137: Jest setup.

### PR DESCRIPTION
**Pull request by nefi-cenfo**
This is the setup for Jest which is used for unit testing in Angular.

### CODE REVIEW

**Review by mur-tz — APPROVED** [review]
Jest integration approved.

**Review by kendallduranv — APPROVED** [review]
Paquete instalado Jest

**Review by DieS06 — APPROVED** [review]
Aprobado.

**Review by ichivancrCenfotec — APPROVED** [review]
Aprobado.

**Pull request merged**
